[global]
ca_file = "auth-ca.crt"

[adapter]
name = "cli.zpr.org"
# This config is designed to be used on the host OS.
# So attaches to the exposed dock port.
node_addr = "127.0.0.1:65000"
node_public_key_file = "node-noise-pub.pem"

[authentication]
# This uses BAS to authenticate.
bas_key = "adapter-cli-bas.key"








