[global]
name = "vs"
ca_file = "auth-ca.crt"
certificate_file = "adapter-vs-noise.crt"
private_key_file = "adapter-vs-noise.key"
zpr_addr = [ "fd5a:5052::2" ] # visa service well known addr
self_addr = "129.6.7.2:5000"
tun_if = "tun9"

[adapter]
node_addr = "129.6.7.1:5000"
node_public_key_file = "node-noise-pub.pem"
bootstrap_key = "vs-zpr-rsa-key.pem"
